Updated `reduce_sum` docs to reflect addition of `lupmf`
stan-dev/example-models pull request #188
Opened 2020-10-23 21:25 UTC by bbbales2

I'm leaving this as a draft until the rest of the `lupmf` docs get in (this will need to link to them)

2020-11-12 14:01 UTC, bbbales2 commented
@wds15 can you review this? It's lupmfs for `reduce_sum`

2020-11-12 14:19 UTC, rok-cesnovar reviewed
Maybe mention that in order to use this you need Stan 2.25+?

2020-11-12 14:23 UTC, bbbales2 commented
@rok-cesnovar good call updating now

2020-11-13 20:34 UTC, rok-cesnovar requested changes
Minor review comments.

2020-11-13 20:34 UTC, rok-cesnovar commented on knitr/reduce-sum/reduce_sum_tutorial.Rmd
> +Note we used `binomial_logit_lupmf` instead of `binomial_logit_lpmf`.
we use or are using? But I am not a native speaker so :shrug:

2020-11-13 20:34 UTC, rok-cesnovar commented on knitr/reduce-sum/reduce_sum_tutorial.Rmd
> +function (suffixed with `_lpdf` or `_lpmf`).
```suggestion
run noticeably faster. There is a bit of catch here. Stan only allows `_lupmf` in the model block
or in user-defined probability distribution functions. Thus, for us to use `binomial_logit_lupmf` the
function we use with `reduce_sum` will need to be a probability distribution
function (suffixed with `_lpdf` or `_lpmf`).
```

2020-11-13 20:34 UTC, rok-cesnovar commented on knitr/reduce-sum/reduce_sum_tutorial.Rmd
> +function (suffixed with `_lpdf` or `_lpmf`).
This is just a suggestion.

2020-11-13 20:34 UTC, rok-cesnovar commented on knitr/reduce-sum/reduce_sum_tutorial.Rmd
> +whatever you like.
```suggestion
If the difference in the performance of normalized and unnormalized functions is not
relevant for your application, you can call your `reduce_sum` function
whatever you like.
```

2020-11-13 20:34 UTC, rok-cesnovar commented on knitr/reduce-sum/reduce_sum_tutorial.Rmd
> +**Note:** This has been rewritten to use `_lupmf` which requires Cmdstan 2.25.
```suggestion
**Note:** This has been rewritten to use unnormalized distribution functions ( `_lupdf˙/˙_lupmf`) which requires Cmdstan 2.25 or newer.
```

2020-12-02 17:58 UTC, bbbales2 commented
@rok-cesnovar wow took me a long time to get around to this. I think all your edits look good so I did them

2020-12-02 18:41 UTC, rok-cesnovar approved these changes
Looks good!

2020-12-02 18:42 UTC, merged