Feature/basic est update
stan-dev/example-models pull request #191
Opened 2021-01-31 16:33 UTC by andrjohns

Updates the models in ```basic_estimators``` with modern Stan syntax (vectorisation, ```_lupdf```, etc)

New syntax parses in Stanc3 (RStan 2.26) with no warnings or errors.

2021-01-31 16:43 UTC, rok-cesnovar requested changes
Thanks Andrew! Looks great. 

We probably dont need the comment on vectorization as it could just confuse the user.

2021-01-31 16:43 UTC, rok-cesnovar commented on basic_estimators/normal_censored.stan
> +  // Vectorization with truncation is not yet supported
Probably no need for this comment.

2021-01-31 16:43 UTC, rok-cesnovar commented on basic_estimators/normal_truncated.stan
> +  // Truncation not yet available with vectorised distributions
Same as above.

2021-02-01 07:45 UTC, andrjohns commented
Good call! Have updated

2021-02-01 09:30 UTC, rok-cesnovar approved these changes
:tada:

2021-02-01 09:30 UTC, merged

2021-02-01 09:31 UTC, rok-cesnovar commented
Thanks Andrew. I gave you write permission to the repo so you can do the branches here, if that helps you in any way.